# Elite platform configuration
obj-$(CONFIG_SND_I2S_ELITE_SOC) += snd-elite-alsa-i2s.o
snd-elite-alsa-i2s-objs := elite-i2s.o  elite-pcm.o elite-snd.o dummy_codec.o

# Elite-based development kit with WM8900 codec configuration
obj-$(CONFIG_SND_ELITE_WM8900) += snd-elite-alsa-wm8900.o
snd-elite-alsa-wm8900-objs := elite-snd.o

# Elite-based development kit with CS4344 codec configuration
obj-$(CONFIG_SND_ELITE_CS4344) += snd-elite-alsa-cs4344.o
snd-elite-alsa-cs4344-objs := elite-snd.o
