#ifndef _DMX_MODULE_H_
#define _DMX_MODULE_H_



typedef enum {
	IOCTL_INT_STATUS = 0x10,
	IOCTL_INT_CLEAR,
	IOCTL_ERROR_STATUS,
	IOCTL_ERROR_MASKS,
	IOCTL_INT_CONFIG,//to config h/w demux interrupt.
	IOCTL_INIT_FILTER, //overall section filter config
	IOCTL_INIT_TSH,  //init buffer threshold
	IOCTL_DMX_CTRL,
	IOCTL_INIT_VBB,
	IOCTL_INIT_ABB,
	IOCTL_INIT_VIB,
	IOCTL_INIT_SBB,
	IOCTL_GET_VBBRO,//get vbb read offset
	IOCTL_GET_VBBWO,//get vbb write offset,
	IOCTL_GET_VIBRO,
	IOCTL_GET_VIBWO,
	IOCTL_GET_ABBRO,
	IOCTL_GET_ABBWO,
	IOCTL_GET_SBBRO,
	IOCTL_GET_SBBWO,
	IOCTL_GET_VBBLVL,
	IOCTL_GET_VIBLVL,
	IOCTL_GET_ABBLVL,
	IOCTL_GET_SBBLVL,
	IOCTL_SET_VBBOFF,
	IOCTL_SET_VIBOFF,
	IOCTL_SET_ABBOFF,
	IOCTL_SET_SBBOFF,
	IOCTL_SET_FPID, //set filter pid.
	IOCTL_SET_FPAT,//set filter pattern;
	IOCTL_SET_FSTART,//set filter stop
	IOCTL_SET_FSTOP,//set filter stop
	IOCTL_SET_VPID,//set video pid
	IOCTL_SET_APID,//set audio pid
	IOCTL_SET_VSTART,
	IOCTL_SET_ASTART,
	IOCTL_SET_VSTOP,
	IOCTL_SET_ASTOP,
	IOCTL_SET_PCRPID,
	IOCTL_SET_PCRDISABLE,
	IOCTL_SET_CSTART,
	IOCTL_SET_CSTOP,
	IOCTL_SET_CMODE,
	//here for ca
	IOCTL_INIT_CA,
	IOCTL_INIT_EKS,
	IOCTL_SET_CW,
	IOCTL_GET_PCR,
	IOCTL_SET_STC,
	IOCTL_GET_STC,
	IOCTL_SOFT_RESET,
	IOCTL_TURN_OFF,
	IOCTL_GET_CACFG,
}DMX_IOCTL_CMD;



				
#endif

