#
# Makefile for the kernel dtv device drivers.
#
obj-$(CONFIG_ELITE_SMARTCARD) += smartcard.o
obj-$(CONFIG_ELITE_DEMUX0) += dvb_demux0.o
obj-$(CONFIG_ELITE_DEMUX1) += dvb_demux1.o
obj-$(CONFIG_ELITE_DEMUX2) += dvb_demux2.o
obj-$(CONFIG_ELITE_DEMUX3) += dvb_demux3.o
obj-$(CONFIG_ELITE_FRONTEND) += frontend.o
obj-$(CONFIG_ELITE_FRONTPANEL) += prebuild/frontpanel.o
obj-$(CONFIG_ELITE_DTV_MMAP) += dtv_mmap.o
obj-$(CONFIG_ELITE_DEMOD) += demod.o

